#!/usr/bin/env bash
# Transfer file `file` to a server
# scp /path/to/file username@a:/path/to/destination
# Handcoded: scp -i ~/.ssh/id_rsa README.md ubuntu@3.84.158.60:/tmp

path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
brown='\e[0;33m'
reset='\033[0m'
# Argument order
file="$1"
ip="$2"
user="$3"
key="$4"

if [ $# -eq 4 ]; then
	scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
	echo -e "Usage: ${brown}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
fi