#!/usr/bin/env bash

# Transfer file `file` to a server
# scp /path/to/file username@a:/path/to/destination
# Handcoded: scp -i ~/.ssh/id_rsa README.md ubuntu@34.75.10.160:/tmp

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi
