#!/usr/bin/env bash
# Install nginx and use it
# can’t use systemctl for restarting nginx

green='\e[1;32m'
# Update
sudo apt-get -y update
# Install Nginx
sudo apt-get -y install nginx
# start the web server
sudo service nginx start
# Allow the server in firewall
sudo ufw allow 'Nginx HTTP'

echo "Hello World\n" | sudo tee /usr/share/nginx/html/index.html
# Restart the server
sudo service nginx restart

echo -e "\n${green}Completed.${reset} ✅\n"
