#!/usr/bin/env bash

# Install nginx and use it
# can’t use systemctl for restarting nginx

apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Holberton School\n" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
