#!/usr/bin/env bash
# updates hostfile to change locolhost to 127.0.0.2 and FB to 8.8.8.8

cp /etc/hosts hosts_tmp

sed -i s/127.*$/127.0.0.2\\t localhost\\n 8.8.8.8\\tfacebook.com/g hosts_tmp

cp -f hosts_tmp /etc/hosts
