#!/usr/bin/env bash
# Script changes owner from root to nginx
# Listening to port 8080
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data/user nginx' /etc/nginx/nginx.conf
chown nginx:nginx  /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
# Since it is also using the 8080 port
pkill apache2
sudo -u nginx restart service nginx restart